// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: api/proto/service.proto

package user_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State    bool    `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Title    string  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Sum      float32 `protobuf:"fixed32,4,opt,name=sum,proto3" json:"sum,omitempty"`
	Currency uint32  `protobuf:"varint,5,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *Bill) Reset() {
	*x = Bill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bill) ProtoMessage() {}

func (x *Bill) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bill.ProtoReflect.Descriptor instead.
func (*Bill) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *Bill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bill) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

func (x *Bill) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Bill) GetSum() float32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *Bill) GetCurrency() uint32 {
	if x != nil {
		return x.Currency
	}
	return 0
}

type CreateBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill *Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
}

func (x *CreateBillRequest) Reset() {
	*x = CreateBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillRequest) ProtoMessage() {}

func (x *CreateBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillRequest.ProtoReflect.Descriptor instead.
func (*CreateBillRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBillRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

type CreateBillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill *Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
}

func (x *CreateBillResponse) Reset() {
	*x = CreateBillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillResponse) ProtoMessage() {}

func (x *CreateBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillResponse.ProtoReflect.Descriptor instead.
func (*CreateBillResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBillResponse) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

type GetBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBillRequest) Reset() {
	*x = GetBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillRequest) ProtoMessage() {}

func (x *GetBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillRequest.ProtoReflect.Descriptor instead.
func (*GetBillRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetBillRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill *Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
}

func (x *GetBillResponse) Reset() {
	*x = GetBillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillResponse) ProtoMessage() {}

func (x *GetBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillResponse.ProtoReflect.Descriptor instead.
func (*GetBillResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetBillResponse) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

type ReadBillsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadBillsRequest) Reset() {
	*x = ReadBillsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBillsRequest) ProtoMessage() {}

func (x *ReadBillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBillsRequest.ProtoReflect.Descriptor instead.
func (*ReadBillsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{5}
}

type ReadBillsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bills []*Bill `protobuf:"bytes,1,rep,name=bills,proto3" json:"bills,omitempty"`
}

func (x *ReadBillsResponse) Reset() {
	*x = ReadBillsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBillsResponse) ProtoMessage() {}

func (x *ReadBillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBillsResponse.ProtoReflect.Descriptor instead.
func (*ReadBillsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadBillsResponse) GetBills() []*Bill {
	if x != nil {
		return x.Bills
	}
	return nil
}

type UpdateBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill *Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
}

func (x *UpdateBillRequest) Reset() {
	*x = UpdateBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBillRequest) ProtoMessage() {}

func (x *UpdateBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBillRequest.ProtoReflect.Descriptor instead.
func (*UpdateBillRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBillRequest) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

type UpdateBillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill *Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
}

func (x *UpdateBillResponse) Reset() {
	*x = UpdateBillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBillResponse) ProtoMessage() {}

func (x *UpdateBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBillResponse.ProtoReflect.Descriptor instead.
func (*UpdateBillResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBillResponse) GetBill() *Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

type DeleteBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBillRequest) Reset() {
	*x = DeleteBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBillRequest) ProtoMessage() {}

func (x *DeleteBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBillRequest.ProtoReflect.Descriptor instead.
func (*DeleteBillRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBillRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteBillResponse) Reset() {
	*x = DeleteBillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBillResponse) ProtoMessage() {}

func (x *DeleteBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBillResponse.ProtoReflect.Descriptor instead.
func (*DeleteBillResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_service_proto protoreflect.FileDescriptor

var file_api_proto_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x5f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0x70, 0x0a, 0x04, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75,
	0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x3a, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04,
	0x62, 0x69, 0x6c, 0x6c, 0x22, 0x3b, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x62, 0x69,
	0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x5f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69, 0x6c,
	0x6c, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x22, 0x12, 0x0a,
	0x10, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3c, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x62, 0x69, 0x6c, 0x6c, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x05, 0x62, 0x69, 0x6c, 0x6c, 0x73, 0x22,
	0x3a, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x22, 0x3b, 0x0a, 0x12, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x42, 0x69,
	0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2e, 0x0a,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x96, 0x03,
	0x0a, 0x0b, 0x42, 0x69, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x1e, 0x2e, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x1b, 0x2e, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69,
	0x6c, 0x6c, 0x73, 0x12, 0x1d, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69,
	0x6c, 0x6c, 0x12, 0x1e, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42,
	0x69, 0x6c, 0x6c, 0x12, 0x1e, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_service_proto_rawDescOnce sync.Once
	file_api_proto_service_proto_rawDescData = file_api_proto_service_proto_rawDesc
)

func file_api_proto_service_proto_rawDescGZIP() []byte {
	file_api_proto_service_proto_rawDescOnce.Do(func() {
		file_api_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_service_proto_rawDescData)
	})
	return file_api_proto_service_proto_rawDescData
}

var file_api_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_service_proto_goTypes = []interface{}{
	(*Bill)(nil),               // 0: hello_world.Bill
	(*CreateBillRequest)(nil),  // 1: hello_world.CreateBillRequest
	(*CreateBillResponse)(nil), // 2: hello_world.CreateBillResponse
	(*GetBillRequest)(nil),     // 3: hello_world.GetBillRequest
	(*GetBillResponse)(nil),    // 4: hello_world.GetBillResponse
	(*ReadBillsRequest)(nil),   // 5: hello_world.ReadBillsRequest
	(*ReadBillsResponse)(nil),  // 6: hello_world.ReadBillsResponse
	(*UpdateBillRequest)(nil),  // 7: hello_world.UpdateBillRequest
	(*UpdateBillResponse)(nil), // 8: hello_world.UpdateBillResponse
	(*DeleteBillRequest)(nil),  // 9: hello_world.DeleteBillRequest
	(*DeleteBillResponse)(nil), // 10: hello_world.DeleteBillResponse
}
var file_api_proto_service_proto_depIdxs = []int32{
	0,  // 0: hello_world.CreateBillRequest.bill:type_name -> hello_world.Bill
	0,  // 1: hello_world.CreateBillResponse.bill:type_name -> hello_world.Bill
	0,  // 2: hello_world.GetBillResponse.bill:type_name -> hello_world.Bill
	0,  // 3: hello_world.ReadBillsResponse.bills:type_name -> hello_world.Bill
	0,  // 4: hello_world.UpdateBillRequest.bill:type_name -> hello_world.Bill
	0,  // 5: hello_world.UpdateBillResponse.bill:type_name -> hello_world.Bill
	1,  // 6: hello_world.BillService.CreateBill:input_type -> hello_world.CreateBillRequest
	3,  // 7: hello_world.BillService.GetBill:input_type -> hello_world.GetBillRequest
	5,  // 8: hello_world.BillService.ReadBills:input_type -> hello_world.ReadBillsRequest
	7,  // 9: hello_world.BillService.UpdateBill:input_type -> hello_world.UpdateBillRequest
	9,  // 10: hello_world.BillService.DeleteBill:input_type -> hello_world.DeleteBillRequest
	2,  // 11: hello_world.BillService.CreateBill:output_type -> hello_world.CreateBillResponse
	4,  // 12: hello_world.BillService.GetBill:output_type -> hello_world.GetBillResponse
	6,  // 13: hello_world.BillService.ReadBills:output_type -> hello_world.ReadBillsResponse
	8,  // 14: hello_world.BillService.UpdateBill:output_type -> hello_world.UpdateBillResponse
	10, // 15: hello_world.BillService.DeleteBill:output_type -> hello_world.DeleteBillResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_service_proto_init() }
func file_api_proto_service_proto_init() {
	if File_api_proto_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBillsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBillsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_service_proto_goTypes,
		DependencyIndexes: file_api_proto_service_proto_depIdxs,
		MessageInfos:      file_api_proto_service_proto_msgTypes,
	}.Build()
	File_api_proto_service_proto = out.File
	file_api_proto_service_proto_rawDesc = nil
	file_api_proto_service_proto_goTypes = nil
	file_api_proto_service_proto_depIdxs = nil
}
